public enum TokenType
{
    LET, PRINT, 
    IDENTIFIER, NUMBER, DOUBLE, CHAR, STRING, INTERPOLATED_STRING, TRIPLE_STRING,
    PLUS, MINUS, MULTIPLY, DIVIDE, MODULO,
    PLUS_EQUALS, MINUS_EQUALS, MULTIPLY_EQUALS, DIVIDE_EQUALS, MODULO_EQUALS,
    PLUS_PLUS, MINUS_MINUS,
    EQUALS, NEWLINE,
    
    LEFT_PAREN, RIGHT_PAREN,
    LEFT_BRACE, RIGHT_BRACE,
    LEFT_BRACKET, RIGHT_BRACKET,
    
    IF, ELIF, ELSE,
    GREATER, LESS,
    GREATER_EQUAL, LESS_EQUAL,
    EQUAL_EQUAL, NOT_EQUAL,
    
    AND, OR, NOT,
    
    WHILE, FOR, TO, IN,

    FN, RETURN, COMMA, COLON,

    BREAK, CONTINUE,

    USE, DOT, AS,

    NULL, TRUE, FALSE,

    EOF
}